language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - develop

script: npm run travis

after_success:
  - npm run travis:cov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
